IF OBJECT_ID(N'dbo.TB_USUARIO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_USUARIO
    (
        ID_USUARIO BIGINT IDENTITY(1,1) NOT NULL,
        NM_USUARIO NVARCHAR(100) NOT NULL,
        DS_EMAIL NVARCHAR(150) NOT NULL,
        DS_SENHA_HASH NVARCHAR(255) NOT NULL,
        CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO),
        CONSTRAINT UQ_TB_USUARIO_DS_EMAIL UNIQUE (DS_EMAIL)
    );
END;
GO

IF OBJECT_ID(N'dbo.TB_FAZENDA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_FAZENDA
    (
        ID_FAZENDA BIGINT IDENTITY(1,1) NOT NULL,
        ID_USUARIO BIGINT NOT NULL,
        NM_FAZENDA NVARCHAR(150) NOT NULL,
        DS_CIDADE NVARCHAR(100) NOT NULL,
        DS_ESTADO CHAR(2) NOT NULL,
        NR_AREA_HECTARES DECIMAL(10,2) NOT NULL,
        CONSTRAINT PK_TB_FAZENDA PRIMARY KEY (ID_FAZENDA),
        CONSTRAINT FK_TB_FAZENDA_TB_USUARIO
            FOREIGN KEY (ID_USUARIO) REFERENCES dbo.TB_USUARIO(ID_USUARIO) ON DELETE CASCADE,
        CONSTRAINT CK_TB_FAZENDA_NR_AREA_HECTARES CHECK (NR_AREA_HECTARES > 0)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'IX_TB_FAZENDA_ID_USUARIO'
      AND object_id = OBJECT_ID(N'dbo.TB_FAZENDA')
)
BEGIN
    CREATE INDEX IX_TB_FAZENDA_ID_USUARIO ON dbo.TB_FAZENDA(ID_USUARIO);
END;
GO
